// Auto-generated entity names from the scene


/**
 * Object containing all entity names in the scene for autocomplete support.
 */
export enum EntityNames {
  Axe_1 = "Axe 1",
  Barbacue = "Barbacue",
  Barrel_3 = "Barrel 3",
  Binoculars = "Binoculars",
  Bird_s_Nest_Fern_Container = "Bird’s Nest Fern Container",
  Boombox = "Boombox",
  Cacti = "Cacti",
  Cactus_2 = "Cactus 2",
  Cactus_3 = "Cactus 3",
  Cactus_4 = "Cactus 4",
  Cactus_4_2 = "Cactus 4_2",
  Cactus_5 = "Cactus 5",
  Cactus_6 = "Cactus 6",
  Cactus_8 = "Cactus 8",
  Cactus_9 = "Cactus 9",
  Chest = "Chest",
  Construction_Cone = "Construction Cone",
  Construction_Materials = "Construction Materials",
  Construction_Materials_2 = "Construction Materials_2",
  Hammock = "Hammock",
  Outdoor_Box_Lamp = "Outdoor Box Lamp",
  Outdoor_Box_Lamp3 = "Outdoor Box Lamp3",
  Props = "Props",
  Residential_Mailbox = "Residential Mailbox",
  Round_Rug = "Round Rug",
  Wine_Glass = "Wine Glass",
  Wooden_Door = "Wooden Door",
  binoculars_gltf = "binoculars.gltf",
  binoculars_gltf_2 = "binoculars.gltf_2",
  binoculars_gltf_3 = "binoculars.gltf_3",
  binoculars_gltf_4 = "binoculars.gltf_4",
  clouds_gltf = "clouds.gltf",
  errorSign_gltf_2 = "errorSign.gltf_2",
  firework_button_gltf = "firework-button.gltf",
  notice_board_gltf = "notice-board.gltf",
  noticeBoard_flagTag_gltf = "noticeBoard-flagTag.gltf",
  noticeBoard_pigeonDeluxe_gltf = "noticeBoard-pigeonDeluxe.gltf",
  tower_gltf = "tower.gltf",
  trampoline_gltf = "trampoline.gltf",
  trampoline_gltf_2 = "trampoline.gltf_2",
  windSock_gltf_2 = "windSock.gltf_2",
  windVane_gltf_5 = "windVane.gltf_5",
  world_gltf = "world.gltf",
} 
